# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

env:
- TOXENV=py26-dj16-cms30
- TOXENV=py27-dj16-cms30
- TOXENV=py27-dj17-cms30
- TOXENV=py33-dj16-cms30
- TOXENV=py33-dj17-cms30
- TOXENV=py34-dj16-cms30
- TOXENV=py34-dj17-cms30
- TOXENV=py27-dj16-cms31
- TOXENV=py27-dj16-cms32
- TOXENV=py27-dj17-cms31
- TOXENV=py27-dj17-cms32
- TOXENV=py27-dj18-cms31
- TOXENV=py27-dj18-cms32
- TOXENV=py33-dj16-cms31
- TOXENV=py33-dj16-cms32
- TOXENV=py33-dj17-cms31
- TOXENV=py33-dj17-cms32
- TOXENV=py33-dj18-cms31
- TOXENV=py33-dj18-cms32
- TOXENV=py34-dj16-cms31
- TOXENV=py34-dj16-cms32
- TOXENV=py34-dj17-cms31
- TOXENV=py34-dj17-cms32
- TOXENV=py34-dj18-cms31
- TOXENV=py34-dj18-cms32

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/